services:
  fragout:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - ADMIN_PUBKEYS=8dc8688200b447ec2e4018ea5e42dc5d480940cb3f19ca8f361d28179dc4ba5e
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
    volumes:
      - fragout_data:/app/data
      - fragout_db:/app/db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pleb-services

volumes:
  fragout_data:
    driver: local
  fragout_db:
    driver: local

networks:
  pleb-services:
    external: true
